# Gate tools that `just verify` and the git hooks call.
brew "actionlint"
brew "container-structure-test"
brew "cspell"
brew "gitleaks"
brew "hadolint"
brew "lefthook"
brew "markdownlint-cli2"
brew "osv-scanner"
brew "shellcheck"
brew "shfmt"
brew "yamllint"
brew "zizmor"
